
cc_binary(
  name = "diagrams-equalizer",
  srcs = [ "main.cpp", "eq_type.cpp", "eq_type.hpp", "sparse_matrix_iterator.hpp" ],
  deps = [ "@eigen//:inc",
           "@com_google_absl//absl/container:flat_hash_map",
           "@com_google_absl//absl/types:span",
         ]
)
