
# Import http_archive
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Import and load the Bazel rules to build Nix packages.
http_archive(
    name = "io_tweag_rules_nixpkgs",
    strip_prefix = "rules_nixpkgs-0.8.0",
    urls = ["https://github.com/tweag/rules_nixpkgs/archive/v0.8.0.tar.gz"],
)

load("@io_tweag_rules_nixpkgs//nixpkgs:repositories.bzl", "rules_nixpkgs_dependencies")
rules_nixpkgs_dependencies()

load("@io_tweag_rules_nixpkgs//nixpkgs:nixpkgs.bzl", "nixpkgs_git_repository", "nixpkgs_package")

nixpkgs_git_repository(
    name = "nixpkgs",
    revision = "21.11",
    sha256 = "c77bb41cf5dd82f4718fa789d49363f512bb6fa6bc25f8d60902fe2d698ed7cc"
)

nixpkgs_package(
    name = "eigen",
    repositories = { "nixpkgs": "@nixpkgs//:default.nix" },
    build_file_content =
"""
cc_library(
  name = "inc",
  srcs = [],
  includes = ["."],
  hdrs = glob(['include/eigen3/Eigen/**']),
  strip_include_prefix = "include/eigen3",
  visibility = ["//visibility:public"],
)
"""
)
