
# Import http_archive
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Import and load the Bazel rules to build Nix packages.
http_archive(
    name = "io_tweag_rules_nixpkgs",
    strip_prefix = "rules_nixpkgs-0.8.0",
    urls = ["https://github.com/tweag/rules_nixpkgs/archive/v0.8.0.tar.gz"],
)

load("@io_tweag_rules_nixpkgs//nixpkgs:repositories.bzl", "rules_nixpkgs_dependencies")
rules_nixpkgs_dependencies()

load("@io_tweag_rules_nixpkgs//nixpkgs:nixpkgs.bzl", "nixpkgs_git_repository", "nixpkgs_package")

nixpkgs_git_repository(
    name = "nixpkgs",
    revision = "21.11",
    sha256 = "c77bb41cf5dd82f4718fa789d49363f512bb6fa6bc25f8d60902fe2d698ed7cc"
)

# Import and load bazel rules to generate a compile_commands.json
# https://github.com/hedronvision/bazel-compile-commands-extractor
http_archive(
    name = "hedron_compile_commands",
    url = "https://github.com/hedronvision/bazel-compile-commands-extractor/archive/066b29fba13750ca9c9e0d1e1ba075577a399a68.tar.gz",
    strip_prefix = "bazel-compile-commands-extractor-066b29fba13750ca9c9e0d1e1ba075577a399a68",
    sha256 = "64b96599a3b9d8293e9e534f8231919ed15af6fdfdfc46979ac69f2078bec71f",
)
load("@hedron_compile_commands//:workspace_setup.bzl", "hedron_compile_commands_setup")
hedron_compile_commands_setup()
# Re-generate the file by running:
# $ bazel run @hedron_compile_commands//:refresh_all

# Find Eigen in nixpkgs
nixpkgs_package(
    name = "eigen",
    repositories = { "nixpkgs": "@nixpkgs//:default.nix" },
    build_file_content =
"""
cc_library(
  name = "inc",
  srcs = [],
  includes = ["."],
  hdrs = glob(['include/eigen3/Eigen/**']),
  strip_include_prefix = "include/eigen3",
  visibility = ["//visibility:public"],
)
"""
)

# Install Abseil
http_archive(
  name = "com_google_absl",
  urls = ["https://github.com/abseil/abseil-cpp/archive/98eb410c93ad059f9bba1bf43f5bb916fc92a5ea.zip"],
  strip_prefix = "abseil-cpp-98eb410c93ad059f9bba1bf43f5bb916fc92a5ea",
  sha256 = "aabf6c57e3834f8dc3873a927f37eaf69975d4b28117fc7427dfb1c661542a87",
)
